# Generated by Django 3.1.3 on 2020-11-08 01:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='date_shipped',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='has_shipped',
            field=models.BooleanField(default=False),
        ),
    ]
