# Generated by Django 3.1.3 on 2020-11-09 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_auto_20201108_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='package_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shipping.package'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='package_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shipping.package'),
            preserve_default=False,
        ),
    ]
