# Generated by Django 3.1.3 on 2020-11-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0004_auto_20201109_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='machine_serial',
        ),
        migrations.RemoveField(
            model_name='package',
            name='machine_type',
        ),
        migrations.RemoveField(
            model_name='package',
            name='model_number',
        ),
        migrations.AddField(
            model_name='machine',
            name='description',
            field=models.CharField(default='IBM Machine', max_length=50),
            preserve_default=False,
        ),
    ]
